version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - '8001:8001'
    volumes:
      - ./server:/src
      - run_vol:/var/run
      - cache_vol:/var/cache
      - tmp_vol:/tmp
    env_file:
      - ./.env
    command: >
      sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - db
      - redis

  client:
    container_name: client
    build: ./client
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - '3000:3000'
    volumes:
      - ./client:/src
    env_file:
      - ./.env
    command: >
      sh -c "npm install -g npm@latest && npm install && npm run dev"
    depends_on:
      - server
      - db

  db:
    container_name: db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    container_name: redis_db
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  redis_data:
    driver: local
  postgres_data:
    driver: local
