version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - '8000:8000'
    volumes:
      - ./server:/src
      - static_volume:/src/static
      - media_volume:/src/media
    env_file:
      - ./.env
    environment:
      - DJANGO_DEBUG=False
    command: sh -c "sh migrations.sh && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  client:
    container_name: client
    build: ./client
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - '3000:3000'
    volumes:
      - ./client:/src
    command: >
      sh -c "npm install -g npm@latest && npm install && npm run build && npm run start"
    depends_on:
      - server

  db:
    container_name: db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    container_name: redis_db
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
