import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

import { MainNav } from '@/components/navbar'
import { ThemeProvider } from '@/components/theme-provider'

// const poppins = Poppins({ subsets: ['latin'] })

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={poppins.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div>
            <MainNav />
          </div>
        </ThemeProvider>
        {/* {children} */}
      </body>
    </html>
  )
}
